Handle occasional failure on first instance tag query
Fix for following error:

    job = run.make_job(job_name, num_tasks=num_tasks, instance_type=args.instance_type, placement_group=args.placement_group, use_spot=args.spot)
  File "/Users/yaroslav/Dropbox/git0/cluster/pytorch-cifar/../aws_backend.py", line 185, in make_job
    skip_efs_mount=skip_efs_mount)
  File "/Users/yaroslav/Dropbox/git0/cluster/pytorch-cifar/../aws_backend.py", line 243, in __init__
    task_id, current_job_name = u.get_parsed_job_name(instance.tags) # use job name in case ami's were not launched at the same time
  File "/Users/yaroslav/anaconda/envs/gpubox/lib/python3.6/site-packages/boto3/resources/factory.py", line 339, in property_loader
    self.load()
  File "/Users/yaroslav/anaconda/envs/gpubox/lib/python3.6/site-packages/boto3/resources/factory.py", line 505, in do_action
    response = action(self, *args, **kwargs)
  File "/Users/yaroslav/anaconda/envs/gpubox/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/Users/yaroslav/anaconda/envs/gpubox/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/yaroslav/anaconda/envs/gpubox/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidInstanceID.NotFound) when calling the DescribeInstances operation: The instance ID 'i-0341f7de0817f8ae6' does not exist